config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # root 'welcome#index'


  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts
  end
  root 'groups#index'

  namespace :account do
    resources :groups
    resources :posts
  end
  # 顺序无所谓的
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :posts

  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user

end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :group
  belongs_to :user

  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true

  scope :recent, -> { order("created_at DESC")}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
  has_many :posts

  has_many :group_relationships
  has_many :participated_groups, through: :group_relationships, source: :group
  # has_many :participated_groups, :through => :group_relationships, :source => :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = current_user.posts
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    # @posts = @group.posts
    # @posts = @group.posts.order("created_at DESC")
      # @posts = @group.posts.recent
      # @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 5) 换一种写法
        @posts = @group.posts.recent.paginate(page: params[:page], per_page: 5)
        # class: "btn btn-primary", :class => "btn btn-primary",
  end

  def edit

  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save

      # 以下是完成建立 group 后自动成为 group 的一员
      current_user.join!(@group)
      # 其实是引用了user.rb中
      # def join!(group)
      #     participated_groups << group
      #   end

    redirect_to groups_path
    else
      render :new
    end
  end

  def update


    if @group.update(group_params)
    redirect_to groups_path, notice: "update success"
  else
    render :edit
  end
  end

  def destroy
    @group.destroy
    flash[:alert] = "group deleted"
    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "welcome to this topic and be team member"
    else
      flash[:warning] = "u already be team member"
      # 上面这条flash语句 只有在rails c里面修改过属性 才会出现 否则逻辑上不会有这种情况
    end
    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
    flash[:alert] = "quit the door and be free"
  else
    flash[:warning] = "you are not team member how to quit"
    # 上面这条flash语句 只有在rails c里面修改过属性 才会出现 否则逻辑上不会有这种情况
  end
    redirect_to group_path(@group)
  end
private


  def find_group_and_check_permission
    @group = Group.find(params[:id])
    if current_user != @group.user
      redirect_to root_path, alert: "you have no permission"
    end
  end

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def new
  @group = Group.find(params[:group_id])
  @post = Post.new
end

def create
  @group = Group.find(params[:group_id])
  @post = Post.new(post_params)
  @post.group = @group
# @post.group_id = @group.id
  @post.user = current_user
# @post.user_id = current_user.id
  if @post.save
    redirect_to group_path(@group)
  else
    render :new
  end
end

def edit
  @group = Group.find(params[:group_id])
  @post = Post.find(params[:id])
end

def update
  # @group = Group.find(params[:group_id])
  @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to account_posts_path, notice: "update success"
    else
      render :edit
    end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  flash[:alert] = "post deleted"
  redirect_to account_posts_path
end

private
def post_params
  params.require(:post).permit(:content)
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = 'welcome to the rails104 success'
    flash[:warning] = 'welcome to the rails104 warning'
    flash[:alert] = 'welcome to the rails104 danger'
  end

end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = {alert: 'danger', notice: 'success', warning: 'warning'}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def render_group_description(group)
    simple_format(group.description)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismis="alert">x </button>
      <%= value %>

    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">@Rails104
    <br>design by
    <a href="http://github.com/szwang147" target="_new">vand</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class='navbar navbar-default' role='navigation'>
  <div class="container-fluid">
  <!-- brand and toggle get group get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 104</a>
    </div>

  <!-- collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li><%= link_to('sign up', new_user_registration_path) %></li>
        <li><%= link_to('log in', new_user_session_path) %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            hi, <%= current_user.email   %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to('my groups', account_groups_path) %></li>
            <li> <%= link_to('my posts', account_posts_path) %></li>
            <li class="divider"></li>
            <li><%= link_to('log out', destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
        <% end %>



      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/groups/_form.html.erb
<!--  使用form样式 -->

<!-- <%#= form_for @group do |f| %>

<%# if @group.errors.any? %>
<ul>
  <%# @group.errors.full_messages.each do |msg| %>
  <li><%##= msg %></li>
  <%# end %>
</ul>
<%# end %>

content
<%#= f.text_field :title %>
<br>
description
<br>
<%#= f.text_area :description %>
<br>

<%#= f.submit "submit", disable_with: "submitting" %>
<%#= end %> -->


<!--  使用bootstrap样式 -->

<!-- <%#= form_for @group do |f| %>
<div class="form-group">
  <div class="form-group string optional">
    <%#= f.label "title", class: "string optional control-label" %>
    <%#= f.label "title", :class => "string optional control-label" %>
    <%#= f.text_field :title, class: "string optional form-control " %>
  </div>

  <div class="form-gourp string optional">
    <%#= f.label "description", class: "string optional control-label" %>
    <%#= f.text_area :description, class: "string optional form-control" %>
  </div>

</div>
<%#= f.submit "submit", :class => "btn btn-primary", data: {disable_with: "submitting"} %>
<%# end %> -->

<!--  使用simple_form样式 -->

<%= simple_form_for @group do |f| %>
<div class="form-group">
  <%= f.input :title, input_html: { class: "form-control"} %>
  <%= f.input :description, input_html: { class: "form-control"} %>
</div>
<%= f.submit "submit", class: "btn btn-primary", data: { disable_with: "submitting"} %>
<% end %>

app/views/groups/_group_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(group.title, group_path(group)) %></td>
  <!-- <td><%#= group.description %></td> -->
  <!-- <td><%#= simple_format(group.description) %></td> -->
  <!-- 加入simple_format 这个helper -->
  <td> <%= render_group_description(group) %></td>
  <!-- 楼上使用了 加入自定义helper -->
  <td><%= group.user.email %></td>
  <td>
    <% if current_user && current_user == group.user %>
    <%= link_to('Edit', edit_group_path(group), class: "btn btn-danger",) %>
    <%= link_to("Delete", group_path(group), class: "btn btn-danger",
      method: :delete, data: {confirm: "are you sure to delete?"})%>
    <% end %>
  </td>
</tr>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Edit the topic</h2>
  <hr>
  <%= render "form" %>

</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to('new group', new_group_path, class: 'btn btn-primary pull-right') %>

  </div>
<table class="table table-hover">
  <thead>
    <tr>
      <td>#</td>
      <td>title</td>
      <td>description</td>
      <td>creator</td>
    </tr>
  </thead>

<tbody>
  <%= render partial: 'group_item', collection: @groups, as: :group  %>
</tbody>

</table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>Add new topic</h2>
  <hr>
  <%= render "form" %>

</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
<!-- 以下是对user进行成员的判断 -->
    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@group) %>
      <label class="label label-success">team member </label>
      <%= link_to('quit group', quit_group_path(@group), method: :post, class: "btn btn-primary") %>
      <% else %>
      <label class="label label-warning">not team member </label>
      <%= link_to('join group', join_group_path(@group), method: :post, class: "btn btn-primary") %>
      <% end %>
    </span>

    <%= link_to('write a post', new_group_post_path(@group), class: 'btn btn-warning pull-right') %>
    <% if current_user && current_user == @group.user %>
    <%= link_to("edit", edit_group_path(@group), class: 'btn btn-primary pull-right') %>
    <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

<!-- 以下是post的相关内容 -->
<table class="table">
  <thead>
    <tr>
      <th>article content</th>
      <th>creator</th>
      <th>creator time</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>
        <td><%= post.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @posts %>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails104</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'common/navbar' %>
      <%= render 'common/flashes' %>
        <%= yield %>
    </div>
   <%= render 'common/footer' %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h2 class="text-center">edit my post which i have posted</h2>

  <div class="col-md-4 col-md-offset-4">

    <%= simple_form_for [@group, @post] do |f| %>
    <!-- 为了到达group_post_path -->

    <div class="form-group">
    <%= f.input :content, input_html: { class: "form-control"} %>
    </div>

    <div class="form-actions">
        <%= f.submit "submit", class: "btn btn-primary", data: { disable_with: "submitting"} %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h2 class="text-center">add new article</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@group, @post] do |f| %>

<div class="form-group">
  <%= f.input :content, input_html: { class: 'form-control'} %>
</div>

<div class="form-actions">
  <%= f.submit "submit", disable_with: "submitting", class: "btn btn-primary" %>
</div>

<% end %>

</div>

app/views/welcome/index.html.erb
<h1> hello world! </h1>